### ISSUE TITLE
Icon style remains after refresh

### ISSUE THREAD

**Issue by Ramerono** [blueriq/blueriq-material#2]
I modeled two buttons with presentationstyles tertiary and icon_check_circle. At refresh the styles are removed from one button and added to the other. While loading the page the style is placed correctly, but after refresh the color is set correctly but the icon still remains on the button even though the json says otherwise. See the picture.

{
	"events": [{
			"sessionId": "e0f8c7cf-f9ec-415f-a5f3-5f09dfd36c44",
			"changes": {
				"changes": [{
						"type": "update",
						"key": "P795-C4-C1-C0-C0-C0-C1-C0-B1",
						"model": {
							"key": "P795-C4-C1-C0-C0-C0-C1-C0-B1",
							"functionalKey": "P795_Kies_2",
							"name": "Kies",
							"properties": {},
							"disabled": false,
							"refresh": false,
							"caption": "Kies",
							"validate": false,
							"type": "button",
							"styles": []
						}
					}, {
						"type": "update",
						"key": "P795-C4-C1-C0-C0-C0-C0-C0-B1",
						"model": {
							"key": "P795-C4-C1-C0-C0-C0-C0-C0-B1",
							"functionalKey": "P795_Kies_1",
							"name": "Kies",
							"properties": {},
							"disabled": false,
							"refresh": false,
							"caption": "Kies",
							"validate": false,
							"type": "button",
							"styles": ["Tertiary", "icon_check_circle"]
						}
					}
				]
			},
			"type": "page"
		}
	]
}

![Schermafbeelding 2019-05-21 om 16 31 28](https://user-images.githubusercontent.com/5764090/58110920-bb860200-7bf0-11e9-947f-a36b6d190c0c.png)

![Schermafbeelding 2019-05-21 om 16 31 34](https://user-images.githubusercontent.com/5764090/58110921-bc1e9880-7bf0-11e9-893d-c0ad353325e2.png)

**Comment by JoostK** [comment]
Thanks for reporting! Looks like the issue is here:

https://github.com/blueriq/blueriq-material/blob/8f54b8c11c857e5445ce608650b132230bbb3b37/src/app/shared/directive/icon/icon.directive.ts#L38

There needs to be an `else` block there to clear `this._class`:

```typescript
} else {
  this._class = null;
}
```

You could probably fix this in your fork, we'll fix it in this repo soon (we don't currently accept PRs, unfortunately).

**Comment by Ramerono** [comment]
Thanks for the help!
