### ISSUE TITLE
input-field.component.html doesn't apply presentation styles

### ISSUE THREAD

**Issue by tomschut** [blueriq/blueriq-material#3]
<mat-form-field bqKey bqClasses fxFlex appearance="fill"> has a bqClasses element. This is not respected if I put a presentation style on a string field. If I add bqClasses to the <p> it however is.

**Comment by raouldh** [comment]
Please clarify your issue.

**Comment by tomschut** [comment]
i have a string field in blueriq. it has the style 'uppercase'.. I expect to see this style in the classlist of the mat-form-field because it is bound to the element and has a bqClasses directive applied. It isn't there.

**Comment by raouldh** [comment]
Please see Report a problem on the Blueriq community
